### ISSUE TITLE
Endpoint configuration types

### ISSUE THREAD

**Issue by Pavel910** [serverless-components/aws-api-gateway#11]
When API is being deployed, it is created as an `edge-optimized` API by default. It is  ok if you are not planning to manually setup another CloudFront distribution yourself. In my case, I do need a custom CF distribution, which makes each request travel through 2 CF distributions: first one being your custom CF, and the second one being the hidden distribution created for `edge-optimized` API Gateway. 

A great description of this is given in this [StackOverflow post](https://stackoverflow.com/a/49845124/6149915).

So my suggestion is to introduce an `endpointTypes` parameter to be able to deploy `REGIONAL` API Gateway, when you know you will deploy a custom CDN:

```yml
api:
  component: "@serverless/aws-api-gateway"
  inputs:
    name: "GraphQL API"
    endpointTypes: ["REGIONAL"]
    stage: prod
    endpoints:
      - path: /graphql
        method: ANY
        function: ${gateway}
    # ... more endpoints ...
```

(since it is specific to AWS, I'm using the `aws-api-gateway` component, I have no idea how this would look in a multi-cloud environment with `@serverless/api` component 🤔 ).

@eahefnawy I would like to hear you opinion on this and if you agree I'd send a PR.
